### ISSUE TITLE
Register size is an invalid option for modbus

### ISSUE THREAD

**Issue by jpombas** [nikito7/han-dev#1]
Boa tarde @nikito7,

Tentei implementar a tua versão do modbus como custom component, no entanto ao incluir o regsiter_size, aparece o seguinte erro:

Invalid config for [modbus]: [register_size] is an invalid option for [modbus]. Check: modbus->modbus->0->sensors->0->register_size. (See /config/configuration.yaml, line 231).

**Comment by nikito7** [comment]
Corre isto:

```js
sed -i -e 's/\"name\": \"Modbus\",/\"name\": \"Modbus\",\n  \"version\": \"21.6.02\",/g' manifest.json
```

Ou simplesmente adiciona o version no manifest

**Comment by jpombas** [comment]
> Corre isto:
> 
> ```js
> sed -i -e 's/\"name\": \"Modbus\",/\"name\": \"Modbus\",\n  \"version\": \"21.6.02\",/g' manifest.json
> ```
> 
> Ou simplesmente adiciona o version no manifest

Perfeito, azelhice minha :)

Obrigado
